### ISSUE TITLE
Utils.isValidClassicAddress is not a function

### ISSUE THREAD

**Issue by xana-rahmani** [xpring-eng/Xpring-JS#1106]
If I run this: 

```
const { Utils } = require('xpring-js')

const rippleClassicAddress = 'rnysDDrRXxz9z66DmCmfWpq4Z5s4TyUP3G'
Utils.isValidClassicAddress(rippleClassicAddress)

```

I get thsi error:

```
TypeError: Utils.isValidClassicAddress is not a function
    at Object.<anonymous> (index.js:31:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by intelliot** [comment]
This function has been replaced with an implementation in xrpl.js: https://js.xrpl.org/modules.html#isValidClassicAddress
